version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
